10 REM INSTRUCTIONS FOR "SUPER STARTREK"  MAR 5, 1978
20 FOR I=1 TO 12:PRINT:NEXT I
25 PRINT CHR$(26)
30 PRINT TAB(10);"*************************************"
40 PRINT TAB(10);"*                                   *"
50 PRINT TAB(10);"*                                   *"
60 PRINT TAB(10);"*      * * SUPER STAR TREK * *      *"
70 PRINT TAB(10);"*                                   *"
80 PRINT TAB(10);"*                                   *"
90 PRINT TAB(10);"*************************************"
100 FOR I=1 TO 8:PRINT:NEXT I
110 INPUT "DO YOU NEED INSTRUCTIONS (Y/N)";K$:IF K$="N" THEN 1210
120 PRINT CHR$(26)
130 PRINT "NOTE:  YOU MUST BE RUNNING 40K CP/M TO RUN STARTREK."
140 PRINT "       THIS MEANS THAT BASIC MUST HAVE ABOUT 18K OF FREE MEMORY."
150 PRINT
160 PRINT"   INSTRUCTIONS FOR 'SUPER STAR TREK'"
170 PRINT
180 PRINT"1. WHEN YOU SEE \COMMAND ?\ PRINTED, ENTER ONE OF THE LEGAL"
190 PRINT"     COMMANDS (NAV,SRS,LRS,PHA,TOR,SHE,DAM,COM, OR XXX)."
200 PRINT"2. IF YOU SHOULD TYPE IN AN ILLEGAL COMMAND, YOU'LL GET A SHORT" 
210 PRINT"     LIST OF THE LEGAL COMMANDS PRINTED OUT."
220 PRINT"3. SOME COMMANDS REQUIRE YOU TO ENTER DATA (FOR EXAMPLE, THE"
230 PRINT"     'NAV' COMMAND COMES BACK WITH 'COURSE (1-9) ?'.)  IF YOU"
240 PRINT"     TYPE IN ILLEGAL DATA (LIKE NEGATIVE NUMBERS), THAT COMMAND"
250 PRINT"     WILL BE ABORTED"
260 PRINT
270 PRINT"     THE GALAXY IS DIVIDED INTO AN 8 X 8 QUADRANT GRID,"
280 PRINT"AND EACH QUADRANT IS FURTHER DIVIDED INTO AN 8 X 8 SECTOR GRID."
290 PRINT
300 PRINT"     YOU WILL BE ASSIGNED A STARTING POINT SOMEWHERE IN THE"
310 PRINT"GALAXY TO BEGIN A TOUR OF DUTY AS COMMANDER OF THE STARSHIP"
320 PRINT"\ENTERPRISE\; YOUR MISSION: TO SEEK AND DESTROY THE FLEET OF"
330 PRINT"KLINGON WARWHIPS WHICH ARE MENACING THE UNITED FEDERATION OF"
340 PRINT"PLANETS."
350 PRINT
352 LINE INPUT "ENTER [CR] TO CONTINUE";A$:IF A$="" THEN PRINT CHR$(26)
360 PRINT"     YOU HAVE THE FOLLOWING COMMANDS AVAILABLE TO YOU AS CAPTAIN"
370 PRINT"OF THE STARSHIP ENTERPRISE:"
380 PRINT
390 PRINT"\NAV\ COMMAND = WARP ENGINE CONTROL --"
400 PRINT"     COURSE IS IN A CIRCULAR NUMERICAL      4  3  2"
410 PRINT"     VECTOR ARRANGEMENT AS SHOWN             . . ."
420 PRINT"     INTEGER AND REAL VALUES MAY BE           ..."
430 PRINT"     USED.  (THUS COURSE 1.5 IS HALF-     5 ---*--- 1"
440 PRINT"     WAY BETWEEN 1 AND 2                      ..."
450 PRINT"                                             . . ."
460 PRINT"     VALUES MAY APPROACH 9.0, WHICH         6  7  8"
470 PRINT"     ITSELF IS EQUIVALENT TO 1.0"
480 PRINT"                                            COURSE"
490 PRINT"     ONE WARP FACTOR IS THE SIZE OF "
500 PRINT"     ONE QUADTANT.  THEREFORE, TO GET"
510 PRINT"     FROM QUADRANT 6,5 TO 5,5, YOU WOULD"
520 PRINT"     USE COURSE 3, WARP FACTOR 1."
530 PRINT:PRINT
531 LINE INPUT "ENTER [CR] TO CONTINUE";A$:IF A$="" THEN PRINT CHR$(26)
540 PRINT"\SRS\ COMMAND = SHORT RANGE SENSOR SCAN"
550 PRINT"     SHOWS YOU A SCAN OF YOUR PRESENT QUADRANT."
560 PRINT
570 PRINT"     SYMBOLOGY ON YOUR SENSOR SCREEN IS AS FOLLOWS:"
580 PRINT"        <*> = YOUR STARSHIP'S POSITION"
590 PRINT"        +K+ = KLINGON BATTLE CRUISER"
600 PRINT"        >!< = FEDERATION STARBASE (REFUEL/REPAIR/RE-ARM HERE!)"
610 PRINT"         *  = STAR"
620 PRINT
630 PRINT"     A CONDENSED 'STATUS REPORT' WILL ALSO BE PRESENTED."
640 PRINT
650 PRINT"\LRS\ COMMAND = LONG RANGE SENSOR SCAN"
660 PRINT"     SHOWS CONDITIONS IN SPACE FOR ONE QUADRANT ON EACH SIDE"
670 PRINT"     OF THE ENTERPRISE (WHICH IS IN THE MIDDLE OF THE SCAN)"
680 PRINT"     THE SCAN IS CODED IN THE FORM \###\, WHERE TH UNITS DIGIT"
690 PRINT"     IS THE NUMBER OF STARS, THE TENS DIGIT IS THE NUMBER OF"
700 PRINT"     STARBASES, AND THE HUNDRESDS DIGIT IS THE NUMBER OF"
710 PRINT"     KLINGONS."
720 PRINT
730 PRINT"     EXAMPLE - 207 = 2 KLINGONS, NO STARBASES, & 7 STARS."
740 PRINT:PRINT
741 LINE INPUT "ENTER [CR] TO CONTINUE";A$:IF A$="" THEN PRINT CHR$(26)
750 PRINT"\PHA\ COMMAND = PHASER CONTROL."
760 PRINT"     ALLOWS YOU TO DESTROY THE KLINGON BATTLE CRUISERS BY "
770 PRINT"     ZAPPING THEM WITH SUITABLY LARGE UNITS OF ENERGY TO"
780 PRINT"     DEPLETE THEIR SHIELD POWER.  (REMEMBER, KLINGONS HAVE"
790 PRINT"     PHASERS TOO!)"
800 PRINT
810 PRINT"\TOR\ COMMAND = PHOTON TORPEDO CONTROL"
820 PRINT"     TORPEDO COURSE IS THE SAME AS USED IN WARP ENGINE CONTROL"
830 PRINT"     IF YOU HIT THE KLINGON VESSEL, HE IS DESTROYED AND"
840 PRINT"     CANNOT FIRE BACK AT YOU.  IF YOU MISS, YOU ARE SUBJECT TO"
850 PRINT"     HIS PHASER FIRE.  IN EITHER CASE, YOU ARE ALSO SUBJECT TO "
860 PRINT"     THE PHASER FIRE OF ALL OTHER KLINGONS IN THE QUADRANT."
870 PRINT
880 PRINT"     THE LIBRARY-COMPUTER (\COM\ COMMAND) HAS AN OPTION TO "
890 PRINT"     COMPUTE TORPEDO TRAJECTORY FOR YOU (OPTION 2)"
900 PRINT
910 PRINT"\SHE\ COMMAND = SHIELD CONTROL"
920 PRINT"     DEFINES THE NUMBER OF ENERGY UNITS TO BE ASSIGNED TO THE"
930 PRINT"     SHIELDS.  ENERGY IS TAKEN FROM TOTAL SHIP'S ENERGY.  NOTE"
940 PRINT"     THAT THE STATUS DISPLAY TOTAL ENERGY INCLUDES SHIELD ENERGY"
950 PRINT
951 LINE INPUT "ENTER [CR] TO CONTINUE";A$:IF A$="" THEN PRINT CHR$(26)
960 PRINT"\DAM\ COMMAND = DAMMAGE CONTROL REPORT"
970 PRINT"     GIVES THE STATE OF REPAIR OF ALL DEVICES.  WHERE A NEGATIVE"
980 PRINT"     'STATE OF REPAIR' SHOWS THAT THE DEVICE IS TEMPORARILY"
990 PRINT"     DAMAGED."
1000 PRINT
1010 PRINT"\COM\ COMMAND = LIBRARY-COMPUTER"
1020 PRINT"     THE LIBRARY-COMPUTER CONTAINS SIX OPTIONS:"
1030 PRINT"     OPTION 0 = CUMULATIVE GALACTIC RECORD"
1040 PRINT"        THIS OPTION SHOWES COMPUTER MEMORY OF THE RESULTS OF ALL"
1050 PRINT"        PREVIOUS SHORT AND LONG RANGE SENSOR SCANS"
1060 PRINT"     OPTION 1 = STATUS REPORT"
1070 PRINT"        THIS OPTION SHOWS THE NUMBER OF KLINGONS, STARDATES,"
1080 PRINT"        AND STARBASES REMAINING IN THE GAME."
1090 PRINT"     OPTION 2 = PHOTON TORPEDO DATA"
1100 PRINT"        WHICH GIVES DIRECTIONS AND DISTANCE FROM THE ENTERPRISE"
1110 PRINT"        TO ALL KLINGONS IN YOUR QUADRANT"
1115 PRINT:PRINT
1116 LINE INPUT "ENTER [CR] TO CONTINUE";A$:IF A$="" THEN PRINT CHR$(26)
1117 PRINT"\COM\ COMMAND = LIBRARY-COMPUTER"
1118 PRINT
1120 PRINT"     OPTION 3 = STARBASE NAV DATA"
1130 PRINT"        THIS OPTION GIVES DIRECTION AND DISTANCE TO ANY "
1140 PRINT"        STARBASE WITHIN YOUR QUADRANT"
1150 PRINT"     OPTION 4 = DIRECTION/DISTANCE CALCULATOR"
1160 PRINT"        THIS OPTION ALLOWS YOU TO ENTER COORDINATES FOR"
1170 PRINT"        DIRECTION/DISTANCE CALCULATIONS"
1180 PRINT"     OPTION 5 = CALACTIC /REGION NAME/ MAP"
1190 PRINT"        THIS OPTION PRINTS THE NAMES OF THE SIXTEEN MAJOR "
1200 PRINT"        GALACTIC REGIONS REFERRED TO IN THE GAME."
1210 PRINT:PRINT:PRINT
1220 PRINT "...CHAINING TO STARTREK..."
1230 LOAD "STARTREK.BAS",R
1240 END
